import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { api } from '../services/api';
import PostCard from '../components/PostCard';

export default function Feed() {
  const [posts, setPosts] = useState([]); const [content, setContent] = useState('');
  const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const user = JSON.parse(localStorage.getItem('user') || '{}'); const navigate = useNavigate();
  useEffect(() => { api('/posts').then(setPosts).catch((err) => { if (err.message.includes('sessão')) { localStorage.clear(); navigate('/login'); } else setError(err.message); }).finally(() => setLoading(false)); }, [navigate]);
  async function publish(event) { event.preventDefault(); if (!content.trim()) return; try { const post = await api('/posts', { method: 'POST', body: JSON.stringify({ content }) }); setPosts((current) => [post, ...current]); setContent(''); } catch (err) { setError(err.message); } }
  function logout() { localStorage.clear(); navigate('/login'); }
  return <div className="app-shell"><aside className="sidebar"><div className="side-logo">𝕏</div><nav><a className="active">⌂ <span>Início</span></a><a>⌕ <span>Explorar</span></a><a>♧ <span>Notificações</span></a><a>✉ <span>Mensagens</span></a></nav><button className="post-cta" onClick={() => document.querySelector('.composer textarea')?.focus()}>Postar</button><div className="profile"><div className="avatar">{user.name?.[0]?.toUpperCase() || '?'}</div><div><strong>{user.name}</strong><small>@{user.username}</small></div><button className="icon-button" onClick={logout} title="Sair">↪</button></div></aside><main className="timeline"><header><h1>Início</h1><span>✦</span></header><form className="composer" onSubmit={publish}><div className="avatar">{user.name?.[0]?.toUpperCase()}</div><div className="compose-body"><textarea maxLength="280" value={content} onChange={(e) => setContent(e.target.value)} placeholder="O que está acontecendo?" /><div className="compose-footer"><span>{content.length}/280</span><button disabled={!content.trim()}>Postar</button></div></div></form>{error && <p className="notice error">{error}</p>}{loading ? <p className="notice">Carregando conversa…</p> : posts.length ? posts.map((post) => <PostCard key={post.id} post={post} onUpdate={(updated) => setPosts((all) => all.map((item) => item.id === updated.id ? updated : item))} onDelete={(id) => setPosts((all) => all.filter((item) => item.id !== id))} />) : <div className="empty"><span>✦</span><h2>Comece a conversa</h2><p>Seu primeiro post pode ser o início de algo interessante.</p></div>}</main><aside className="rightbar"><div className="search">⌕ Buscar</div><section><h2>O que está acontecendo</h2><article><small>Assunto do momento</small><strong>#MiniTwitter</strong><span>1.284 posts</span></article><article><small>Tecnologia · Em alta</small><strong>JavaScript</strong><span>8.921 posts</span></article><article><small>Comunidade</small><strong>#AprendendoAProgramar</strong><span>3.405 posts</span></article></section><footer>Clone educacional · Feito com React e Node.js</footer></aside></div>;
}
